name: Validate PR

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # setup cache
      - name: "Running shasum for cache invalidation"
        run: |
          shasum build.sbt \
            project/plugins.sbt \
            project/build.properties > gha.cache.tmp
      - name: Loading ivy cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-ivy-
      - name: Loading coursier cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-${{ hashFiles('gha.cache.tmp') }}
          restore-keys: |
            ${{ runner.os }}-coursier-

      # setup JDK
      - name: Set up Azul JDK 1.8 and SBT
        uses: olafurpg/setup-scala@v10
        with:
          java-version: zulu@1.8

      # run validation
      - name: Validate
        run: sbt "^validate"
